// World Map Locations — Mapa Północy
// Wszystkie lokacje świata zewnętrznego z questami i danymi Discord bota

const q = (arr) => JSON.stringify(arr);

export const WORLD_SEED_LOCATIONS = [

// ═══════════════════════════════════════════════════════════════════
//  REGION HUBS
// ═══════════════════════════════════════════════════════════════════

  {
    id: 'wl-fortress',
    name: 'Twierdza Durmstrang',
    nordic_name: 'Festung Durmstrang',
    x: 50, y: 48,
    icon: '🏰', type: 'entrance', region: 'Centrum',
    marker_type: 'entrance', visibility: 'visible', state: 'available',
    short_desc: 'Siedziba Twierdzy Magii Durmstrang',
    description_short: 'Kliknij aby wejść do Twierdzy',
    full_lore: 'Monumentalna cytadela wzniesiona na skalnym cyplu nad zamarzniętym fiordem. Za murami Twierdzy kryją się setki korytarzy, sala po sali, tajemnica po tajemnicy. Nie każde drzwi mają klamkę. Nie każdy korytarz prowadzi tam, gdzie myślisz.',
    npcs: q(['Arcymistrzyni Valgerda Storm', 'Strażnik Bramy Hrókr', 'Portier Þórir']),
    actions: q(['Wejdź do Twierdzy', 'Sprawdź tablicę ogłoszeń', 'Zapytaj strażnika bramy']),
    discovery_reward_xp: 20, discovery_reward_skirniry: 10,
    quests: q([
      {
        id: 'quest-wl-fortress-tutorial',
        title: 'Pierwszy dzień w Twierdzy',
        category: 'Tutorial', difficulty: 'Łatwy',
        discordChannel: '#brama-polnocy',
        reward: { points: 10, xp: 30, skirniry: 5 },
        description: 'Każdy adept musi po raz pierwszy przekroczyć Bramę Północy. Strażnik Hrókr prosi o przedstawienie się i okazanie pieczęci zakonu.',
        initialBotMessage: '🏰 **[TMD BOT - BRAMA PÓŁNOCY]**\nStoisz przed ogromną bramą z czarnego żelaza. Strażnik Hrókr spogląda na ciebie spod przyłbicy.\n*„Zakon. Imię. Pieczęć. W tej kolejności."*\n\nOznajmij swoją tożsamość:',
        suggestedActions: [
          { label: '🛡️ Przedstaw się strażnikowi', cmd: '/przedstaw zakon imie' },
          { label: '📜 Okaż pieczęć zakonu', cmd: '/pieczec zakon' },
        ],
        solutionKeywords: ['przedstaw', 'pieczec', 'zakon', 'imie', 'brama'],
        successMessage: '✨ Brama otwiera się z głębokim odgłosem. Hrókr kiwa głową. Twierdza cię przyjęła.',
        failMessage: '❄️ Hrókr blokuje ci przejście. *„Nie bez pieczęci."*',
      },
      {
        id: 'quest-wl-fortress-nocny-intruz',
        title: 'Nocny intruz',
        category: 'Tajemnica', difficulty: 'Średni',
        discordChannel: '#twierdza-tajemnice',
        reward: { points: 25, xp: 70, skirniry: 15 },
        description: 'Strażnik bramy widział kogoś wchodzącego do zamkniętego skrzydła o trzeciej w nocy. Nie był to żaden profesor. Zbadaj sprawę.',
        initialBotMessage: '🏰 **[TMD BOT - ZAMKNIĘTE SKRZYDŁO]**\nKorytarz jest ciemny. Twój lumos odbija się od ścian pokrytych lodem.\n*Świeże ślady butów na mroźnej podłodze.*\n\nCo robisz:',
        suggestedActions: [
          { label: '🔍 Zbadaj ślady', cmd: '/zbadaj slady' },
          { label: '🕯️ Rzuć Lumos Maxima', cmd: '/rzut lumos-maxima' },
          { label: '👂 Nasłuchuj', cmd: '/nasluchuj cisza' },
        ],
        solutionKeywords: ['slady', 'lumos', 'nasluchuj', 'tropienie', 'skrzydlo'],
        successMessage: '✨ Ślady prowadzą do zamurowanych drzwi. Za nimi coś pulsuje słabym, niebieskim światłem.',
        failMessage: '❄️ Korytarz jest już pusty. Intruz zniknął.',
      },
    ]),
  },

// ═══════════════════════════════════════════════════════════════════
//  JÖTUNSKÓG — Czarny Las
// ═══════════════════════════════════════════════════════════════════

  {
    id: 'wl-jotunskogg',
    name: 'Jötunskóg',
    nordic_name: 'Jötunskógr',
    x: 26, y: 50,
    icon: '🌲', type: 'region', region: 'Zachód',
    marker_type: 'location', visibility: 'visible', state: 'available',
    short_desc: 'Czarny Las — ogromny region na zachód od Twierdzy',
    description_short: 'Mroczny las pełen tajemnic i zaginień',
    full_lore: 'Ogromny las starych sosen, gdzie słońce niemal nie dosięga gruntu. Mieszkańcy Fjordgardu omijają go szerokim łukiem. Mówi się, że drzewa tu pamiętają — i że niektórzy, którzy weszli za głęboko, nigdy nie wrócili z tej samej osoby co odeszły.',
    npcs: q(['Zielarka Skadi', 'Duch Strażnika Lasu', 'Biały Jeleń (legendarny)']),
    actions: q(['Eksploruj las', 'Szukaj śladów', 'Zbieraj zioła', 'Nasłuchuj głosów drzew']),
    discovery_reward_xp: 15, discovery_reward_skirniry: 8,
    quests: q([
      {
        id: 'quest-jot-slady',
        title: 'Ślady na śniegu',
        category: 'Eksploracja', difficulty: 'Łatwy',
        discordChannel: '#las-jotun',
        reward: { points: 15, xp: 40, skirniry: 8 },
        description: 'Na skraju Jötunskógu odkryto ślady butów prowadzące w głąb lasu. Strażnik prosi o zbadanie co lub kto je zostawił.',
        initialBotMessage: '🌲 **[TMD BOT - SEKTOR: JÖTUNSKÓG]**\nŚwieże ślady prowadzą między sosnami w kierunku Rozdroża Wisielców.\n*Rozmiar: adepci. Kierunek: w głąb lasu. Czas: dziś rano.*\n\nCo robisz:',
        suggestedActions: [
          { label: '👣 Podążaj śladami', cmd: '/tropienie slady-adept' },
          { label: '🔮 Rzuć Vestigia — odczytaj ślady', cmd: '/rzut vestigia' },
        ],
        solutionKeywords: ['slady', 'tropienie', 'vestigia', 'kierunek', 'podazaj'],
        successMessage: '✨ Ślady prowadzą do porzuconego plecaka przy Rozdrozu Wisielców. To nie było przypadkowe.',
        failMessage: '❄️ Śnieg przysypał ślady. Zacznij od nowa od skraju lasu.',
      },
      {
        id: 'quest-jot-zielarka',
        title: 'Zielarka z lasu',
        category: 'NPC & Zlecenia', difficulty: 'Łatwy',
        discordChannel: '#las-jotun',
        reward: { points: 12, xp: 35, skirniry: 10, item: 'Mikstura Spokoju Lasu' },
        description: 'Zielarka Skadi prosi o trzy składniki — ale podaje tylko połowę wskazówek.',
        initialBotMessage: '🌿 **[TMD BOT - CHATKA ZIELARKI]**\nStara kobieta miesza coś w garnku. Pachnie sosną i siarką.\n*„Trzy rzeczy. Mech z kamienia. Pióro białego ptaka. I coś, czego nie ma w lesie w dzień."*\n\nCo szukasz najpierw:',
        suggestedActions: [
          { label: '🧲 Zbieraj mech z kamiennych bloków', cmd: '/zbierz mech kamien' },
          { label: '🪶 Szukaj białego ptaka', cmd: '/szukaj biale-pioro gniezdo' },
          { label: '🌙 Wróć nocą po trzeci składnik', cmd: '/wyjdz noc powrot' },
        ],
        solutionKeywords: ['mech', 'pioro', 'noc', 'zbierz', 'skladnik', 'zielarka'],
        successMessage: '✨ Zielarka Skadi kiwa głową. *„Dobra robota. Rzadko ktoś wraca z całą listą."*',
        failMessage: '❄️ *„Nie to."* Zielarka odpycha twoje składniki.',
      },
      {
        id: 'quest-jot-kamienie',
        title: 'Kamienie pamiętają',
        category: 'Tajemnica Runiczna', difficulty: 'Średni',
        discordChannel: '#kamienny-krag',
        reward: { points: 30, xp: 80, skirniry: 20 },
        description: 'Kamienny Krąg w głębi Jötunskógu — ktoś przestawił kamienie w ciągu ostatniej nocy.',
        initialBotMessage: '🗿 **[TMD BOT - KAMIENNY KRĄG]**\nSiedem kamieni. Siedem run. Ale jedna runa jest odwrócona.\n*Las jest cicho. Cisza, która boli.*\n\nJaką runę przywrócisz jako pierwszą:',
        suggestedActions: [
          { label: 'ᚦ Thuriszaz — runa siły', cmd: '/runa thurisaz prawidlowa' },
          { label: 'ᚨ Ansuz — runa mądrości', cmd: '/runa ansuz odwroc' },
          { label: '📜 Zbadaj wzór magicznym wykrywaczem', cmd: '/rzut detekcja magia krag' },
        ],
        solutionKeywords: ['runa', 'krag', 'odwroc', 'thuriszaz', 'ansuz', 'wzor'],
        successMessage: '✨ Gdy ostatnia runa wraca na miejsce, las wydycha głęboko. Coś pod ziemią przestało się poruszać.',
        failMessage: '❄️ Zła kolejność. Kamienie drżą i wracają na poprzednie pozycje.',
      },
      {
        id: 'quest-jot-chain-final',
        title: 'To, co obudzono',
        category: 'Quest Chain — Jötunskóg', difficulty: 'Trudny',
        discordChannel: '#kamienny-krag',
        reward: { points: 50, xp: 150, skirniry: 40, item: 'Fragment Inskrypcji Leśnej' },
        description: 'FINAŁ ŁAŃCUCHA: Ślady → plecak → zaginiony uczeń → Czarna Polana → Kamienny Krąg. Ktoś celowo aktywował krąg. Pytanie: co obudził?',
        initialBotMessage: '🗿 **[TMD BOT - KAMIENNY KRĄG · FINAŁ]**\nKamienie drżą. Runy świecą. Nie powinny.\n*Coś wychodzi z ziemi. Coś starego.*\n*„Kto cię tu wysłał?"*\n\nOdpowiedz Strażnikowi Kręgu:',
        suggestedActions: [
          { label: '📜 Recytuj Formułę Uśpienia', cmd: '/inkantacja formula-uspienia' },
          { label: '🤝 Spróbuj nawiązać kontakt', cmd: '/komunikacja straznik-krag' },
          { label: '⚔️ Stań do konfrontacji', cmd: '/stanac konfrontacja straznik' },
        ],
        solutionKeywords: ['formula', 'uspienie', 'kontakt', 'straznik', 'krag', 'inskrypcja'],
        successMessage: '✨ Strażnik milknie. Runy gasną. W miejscu gdzie stał leży kamienna płytka z fragmentem inskrypcji. Jeden z dwunastu.',
        failMessage: '❄️ Krąg wyrzuca cię magicznym uderzeniem. Wróć lepiej przygotowany.',
      },
    ]),
  },

  {
    id: 'wl-jot-skraj',
    name: 'Skraj Jötunskógu',
    nordic_name: 'Skógrmörk',
    x: 31, y: 47,
    icon: '🌲', type: 'poi', region: 'Zachód',
    marker_type: 'poi', visibility: 'visible', state: 'available',
    short_desc: 'Wejście do Czarnego Lasu — tu zaczynają się wszystkie ślady',
    description_short: 'Punkt wejścia do Jötunskógu',
    full_lore: 'Granica między bezpieczeństwem a lasem. Stara tablica z wygrawerowaną runą ostrzegawczą. Miejscowi zostawiają przy niej ofiary — jedzenie, wiązki ziół, czasem różdżkę dziecka, którego nie odzyskali.',
    npcs: q(['Leśny Strażnik Björnar']),
    actions: q(['Przestudiuj tablicę ostrzeżeń', 'Zapytaj strażnika o las', 'Wejdź w głąb']),
    discovery_reward_xp: 8, discovery_reward_skirniry: 3,
    quests: q([
      {
        id: 'quest-jot-skraj-tablica',
        title: 'Tablica Ostrzeżeń',
        category: 'Eksploracja', difficulty: 'Łatwy',
        discordChannel: '#las-jotun',
        reward: { points: 8, xp: 20, skirniry: 3 },
        description: 'Na tablicy przy wejściu wyrzeźbiono runy — ale jedna z nich jest nowa, wyrzeźbiona w nocy.',
        initialBotMessage: '🌲 **[TMD BOT - SKRAJ LASU]**\nTablica jest stara. Ale jedna runa jest wyrzeźbiona świeżo — drewno jasne, bez patyny.\n*„Isa. Runa lodu. Zatrzymanie."*\n\nCo to oznacza i kto to zrobił:',
        suggestedActions: [
          { label: '📖 Odczytaj runę Isa', cmd: '/runologia isa znaczenie' },
          { label: '🔍 Zbadaj narzędzie', cmd: '/zbadaj runa narzedzie' },
          { label: '👥 Zapytaj Bjornara', cmd: '/zapytaj bjornar tablica' },
        ],
        solutionKeywords: ['isa', 'lod', 'runa', 'tablica', 'bjornar'],
        successMessage: '✨ Bjornar: *„To sygnał. Ostatnio ktoś z wewnątrz."*',
        failMessage: '❄️ Runa jest zbyt zamazana. Spróbuj z bliższej odległości.',
      },
    ]),
  },

  {
    id: 'wl-jot-chatka',
    name: 'Chatka Zielarki',
    nordic_name: 'Urtagarðshús',
    x: 19, y: 57,
    icon: '🏚️', type: 'npc', region: 'Zachód',
    marker_type: 'npc', visibility: 'visible', state: 'available',
    short_desc: 'Siedziba Zielarki Skadi — jedynej osoby, która zna las od środka',
    description_short: 'NPC: Zielarka Skadi · zioła · zlecenia',
    full_lore: 'Chatka nie ma adresu. Mapa jej nie pokazuje. Znajdziesz ją, albo nie znajdziesz — i to nie zależy od tego, czy szukasz. Zielarka Skadi spędza więcej czasu z roślinami niż z ludźmi.',
    npcs: q(['Zielarka Skadi']),
    actions: q(['Kup zioła lecznicze', 'Poproś o instrukcje', 'Wymień składniki', 'Zbierz zlecenie']),
    discovery_reward_xp: 12, discovery_reward_skirniry: 6,
    quests: q([]),
  },

  {
    id: 'wl-jot-krag',
    name: 'Kamienny Krąg',
    nordic_name: 'Steinahringr',
    x: 21, y: 44,
    icon: '🗿', type: 'ruins', region: 'Zachód',
    marker_type: 'quest', visibility: 'visible', state: 'available',
    short_desc: 'Pradawny krąg runiczny — węzeł magii leśnej',
    description_short: 'Węzeł magii · questy runiczne · chain Jötunskóg',
    full_lore: 'Siedem kamieni w idealnym okręgu. Runy na każdym z nich tworzą razem jedną inskrypcję, której nikt jeszcze nie odczytał w całości — bo nikt nie był w stanie stanąć tu dostatecznie długo.',
    npcs: q([]),
    actions: q(['Przestudiuj układ run', 'Odczytaj inskrypcję', 'Aktywuj krąg']),
    discovery_reward_xp: 18, discovery_reward_skirniry: 10,
    quests: q([]),
  },

  {
    id: 'wl-jot-zrodlo',
    name: 'Źródło Mímira',
    nordic_name: 'Mímisbrunnr',
    x: 15, y: 53,
    icon: '💧', type: 'secret', region: 'Zachód',
    marker_type: 'secret', visibility: 'hidden', state: 'available',
    short_desc: 'Ukryte źródło — dostępne po ukończeniu chaina Runehaven',
    description_short: 'Sekret · odblokowane po chain Run',
    full_lore: 'Mímir zapłacił okiem za mądrość. Źródło przyjmuje inne ceny. Co możesz oddać za wiedzę, której nikt inny na Północy nie posiada?',
    npcs: q(['Duch Mímira']),
    actions: q(['Zajrzyj w głębię', 'Zanurzenie dłoni', 'Zapytaj Ducha']),
    discovery_reward_xp: 40, discovery_reward_skirniry: 25,
    quests: q([
      {
        id: 'quest-jot-mimir',
        title: 'Cena Wiedzy',
        category: 'Sekret', difficulty: 'Legendarny',
        discordChannel: '#sekrety-polnocy',
        reward: { points: 60, xp: 200, skirniry: 50, item: 'Kropla z Mímisbrunnr' },
        description: 'SEKRET — Źródło Mímira wymaga ofiary. Musisz oddać jedno wspomnienie, aby zdobyć drugie.',
        initialBotMessage: '💧 **[TMD BOT - MÍMISBRUNNR]**\nWoda jest czarna i bez dna. W jej głębi widzisz własną twarz — ale z innych oczu.\n*„Co oddasz?"*\n\nWybierz co poświęcasz:',
        suggestedActions: [
          { label: '🧠 Oddaj wspomnienie z dzieciństwa', cmd: '/ofiara wspomnienie dziecinstwo' },
          { label: '📚 Oddaj naukę którą opanowałeś', cmd: '/ofiara wiedza umiejetnosc' },
          { label: '❤️ Oddaj coś cenniejszego', cmd: '/ofiara cos-cennego' },
        ],
        solutionKeywords: ['ofiara', 'wspomnienie', 'oddaj', 'wiedza', 'cena'],
        successMessage: '✨ Woda pochłania ofiarę. W zamian — obraz: fragment tego czym Skallgard był zanim stał się ruinami.',
        failMessage: '❄️ *„Nie dość."* Źródło milknie.',
      },
    ]),
  },

// ═══════════════════════════════════════════════════════════════════
//  ZAMARZNIĘTY FIORD
// ═══════════════════════════════════════════════════════════════════

  {
    id: 'wl-fiord',
    name: 'Zamarznięty Fiord',
    nordic_name: 'Ísfjörðr',
    x: 62, y: 72,
    icon: '🧊', type: 'region', region: 'Południe',
    marker_type: 'activity', visibility: 'visible', state: 'available',
    short_desc: 'Zamarznięty fiord z wrakami, tajemnicami i aktywnymi lokacjami',
    description_short: 'Połów · wrakosławstwo · tajemnice lodu',
    full_lore: 'Głęboki fiord otoczony klifami z lodu. Pod lodem znaleziono trzy wraki, dwa szkielety i jeden dziennik pokładowy sprzed osiemdziesięciu lat. Dziennik był pisany w języku, który przestał istnieć.',
    npcs: q(['Rybak Ulfhéðinn', 'Latarniczka Sigrid', 'Duch Kapitana Brandra']),
    actions: q(['Idź na połów', 'Poszukaj wraków', 'Sprawdź latarnię', 'Zbadaj klify']),
    discovery_reward_xp: 15, discovery_reward_skirniry: 8,
    linked_activity_type: 'fishing',
    quests: q([
      {
        id: 'quest-fiord-wrak',
        title: 'Wrak Hrimfaxi',
        category: 'Eksploracja & Tajemnica', difficulty: 'Średni',
        discordChannel: '#zamarzniety-fiord',
        reward: { points: 25, xp: 70, skirniry: 18 },
        description: 'Pod lodem widać sylwetkę statku. Hrimfaxi zatonął przed siedemdziesięcioma laty z pełną załogą — ale oficjalnie wypadku nie było.',
        initialBotMessage: '🧊 **[TMD BOT - ZAMARZNIĘTY FIORD]**\nLód jest przeźroczysty jak szkło. Poniżej — maszty, kadłub, i latarnia, która pali się pod wodą.\n\nJak zanurzasz się do wraku:',
        suggestedActions: [
          { label: '🌊 Zaklęcie Aqua Respiratio', cmd: '/rzut aqua-respiratio' },
          { label: '🔨 Rozkrusz lód nad lukiem', cmd: '/przebij lod hrimfaxi-luk' },
          { label: '🔮 Obserwuj przez lodowy teleskop', cmd: '/uzyj lodowy-teleskop wrak' },
        ],
        solutionKeywords: ['wrak', 'hrimfaxi', 'lod', 'latarnia', 'zanurz', 'aqua'],
        successMessage: '✨ Kabina kapitana nienaruszona. Na stole: dziennik pokładowy z ostatnim wpisem sprzed siedemdziesięciu lat.',
        failMessage: '❄️ Lód jest za gruby. Potrzebujesz właściwego zaklęcia.',
      },
      {
        id: 'quest-fiord-syrena',
        title: 'Syrena ze Skały',
        category: 'Legenda', difficulty: 'Trudny',
        discordChannel: '#zamarzniety-fiord',
        reward: { points: 35, xp: 100, skirniry: 25, item: 'Łuska Morskiej Syreny' },
        description: 'Głos ze Skały Syren przy pełni sprawia, że łodzie skręcają w złym kierunku. Trzy statki rozbito w tym roku.',
        initialBotMessage: '🌊 **[TMD BOT - SKAŁA SYREN]**\nPełnia. Woda gładka jak metal. Z odległej skały dochodzi dźwięk — nie śpiew, nie krzyk. Coś pomiędzy.\n*Twoja łódź sama skręca w prawo.*\n\nJak reagujesz:',
        suggestedActions: [
          { label: '🎵 Zaśpiewaj Balladę Blokującą', cmd: '/inkantacja ballada-blokujaca' },
          { label: '🧩 Zatkaj uszy woskiem runicznym', cmd: '/uzyj runiczny-wosk uszy' },
          { label: '🚣 Dotrzyj do skały wbrew prądowi', cmd: '/plyw wbrew syren-skala' },
        ],
        solutionKeywords: ['ballada', 'wosk', 'syren', 'skala', 'blokuj', 'uszy'],
        successMessage: '✨ Na skale: dwie banszatki uwięzione przez dawne zaklęcie. Ich krzyk to rozpacz, nie pieśń. Możesz je uwolnić.',
        failMessage: '❄️ Głos jest za silny. Tracisz kontrolę nad łodzią.',
      },
    ]),
  },

  {
    id: 'wl-fiord-przystan',
    name: 'Przystań Durmstrangu',
    nordic_name: 'Durmstrangshöfn',
    x: 55, y: 70,
    icon: '⚓', type: 'poi', region: 'Południe',
    marker_type: 'activity', visibility: 'visible', state: 'available',
    short_desc: 'Oficjalna przystań Twierdzy — stąd wyruszają łodzie ekspedycyjne',
    description_short: 'Aktywność: połów · wypożyczalnia łodzi',
    full_lore: 'Rybak Ulfhéðinn wypożycza sprzęt wędkarski i dostarcza prowiant. Nie pyta, gdzie płyniesz. To jego największa zaleta.',
    npcs: q(['Rybak Ulfhéðinn']),
    actions: q(['Idź na połów (Aktywność)', 'Wypożycz łódź', 'Kup sprzęt', 'Sprawdź rozkład ekspedycji']),
    discovery_reward_xp: 10, discovery_reward_skirniry: 5,
    linked_activity_type: 'fishing',
    quests: q([]),
  },

  {
    id: 'wl-fiord-latarnia',
    name: 'Latarnia Strażnika',
    nordic_name: 'Vörðuljos',
    x: 58, y: 79,
    icon: '🏮', type: 'poi', region: 'Południe',
    marker_type: 'quest', visibility: 'visible', state: 'available',
    short_desc: 'Stara latarnia morska — obsługiwana przez Sigrid od czterdziestu lat',
    description_short: 'NPC: Sigrid · mapa wraków · tajemnica',
    full_lore: 'Latarnia nigdy nie gaśnie. Latarniczka Sigrid nigdy nie śpi. Ma mapy całego fiordu, włącznie z wrakami, które oficjalnie nie istnieją.',
    npcs: q(['Latarniczka Sigrid']),
    actions: q(['Porozmawiaj z Sigrid', 'Obejrzyj mapy wraków', 'Poproś o przewodnictwo']),
    discovery_reward_xp: 12, discovery_reward_skirniry: 6,
    quests: q([
      {
        id: 'quest-fiord-latarnia-gasniecie',
        title: 'Latarnia, która gaśnie',
        category: 'Tajemnica', difficulty: 'Średni',
        discordChannel: '#zamarzniety-fiord',
        reward: { points: 20, xp: 60, skirniry: 12 },
        description: 'Po raz pierwszy od czterdziestu lat latarnia przygasła na trzy minuty. Sigrid twierdzi, że coś musiało wejść z morza.',
        initialBotMessage: '🏮 **[TMD BOT - LATARNIA STRAŻNIKA]**\nSigrid stoi z latarnią, patrząc na morze.\n*„Coś to zrobiło. Coś, co nie chciało, żebyśmy widzieli co wychodzi z wody."*\n\nCo badasz:',
        suggestedActions: [
          { label: '🔍 Zbadaj mechanizm latarni', cmd: '/zbadaj latarnia mechanizm' },
          { label: '🌊 Sprawdź ślady na brzegu', cmd: '/zbadaj brzeg slady-morskie' },
          { label: '📜 Przejrzyj log Sigrid', cmd: '/czytaj log sigrid' },
        ],
        solutionKeywords: ['latarnia', 'brzeg', 'slady', 'mechanizm', 'sigrid'],
        successMessage: '✨ Na brzegu: wielkie, mokre ślady. Nie ludzkie. Coś dużego wyszło z fiordu gdy latarnia zgasła.',
        failMessage: '❄️ Morze zaciera ślady szybciej niż możesz je zbadać.',
      },
    ]),
  },

// ═══════════════════════════════════════════════════════════════════
//  GÓRY FROSTFANG
// ═══════════════════════════════════════════════════════════════════

  {
    id: 'wl-frostfang',
    name: 'Góry Frostfang',
    nordic_name: 'Frostfangr',
    x: 50, y: 18,
    icon: '⛰️', type: 'region', region: 'Północ',
    marker_type: 'location', visibility: 'visible', state: 'locked',
    short_desc: 'Wysokie góry Północy — region wysokopoziomowy',
    description_short: 'Zablokowany · region wysokopoziomowy',
    full_lore: 'Najwyższe szczyty Północy. Ekspedycja badawcza z poprzedniego roku nie wróciła. Oficjalna wersja: zamieja. Nieoficjalna: nic nie wróciło, bo nie mogło.',
    npcs: q(['Strażnik Przełęczy Gunnar', 'Ostatni Górnik (duch)']),
    actions: q(['Zdaj Próbę Wytrwałości', 'Szukaj zaginionej ekspedycji', 'Wspinaj się na Szczyt Skadi']),
    discovery_reward_xp: 20, discovery_reward_skirniry: 12,
    quests: q([
      {
        id: 'quest-frost-droga',
        title: 'Droga na Frostfang',
        category: 'Eksploracja', difficulty: 'Trudny',
        discordChannel: '#gory-frostfang',
        reward: { points: 30, xp: 90, skirniry: 20 },
        description: 'Dotarcie do Gór Frostfang wymaga przekroczenia Przełęczy. Strażnik Gunnar wpuszcza tylko tych, którzy zdają Próbę Wytrwałości.',
        initialBotMessage: '⛰️ **[TMD BOT - SEKTOR: FROSTFANG]**\nGunnar stoi w śniegu bez futra.\n*„Wielu próbuje. Mało wraca. Nie dlatego, że ginie — dlatego, że rezygnuje."*\n*„Próba Wytrwałości. Zaczynamy."*\n\nJak przechodzisz próbę:',
        suggestedActions: [
          { label: '❄️ Wytrzymaj mróz bez zaklęcia', cmd: '/wytrzymaj mróz bez-magii' },
          { label: '🔥 Użyj Calefactio', cmd: '/rzut calefactio obrone-mrozu' },
          { label: '🧠 Wykaż się wiedzą o górach', cmd: '/wiedza frostfang topografia' },
        ],
        solutionKeywords: ['wytrzymaj', 'calefactio', 'próba', 'gunnar', 'wytrwalosc'],
        successMessage: '✨ Gunnar kiwa głową. *„Nie zginiesz szybko."* W górach Frostfang — to komplement.',
        failMessage: '❄️ Próba nieudana. *„Wróć, gdy będziesz gotowy."*',
      },
      {
        id: 'quest-frost-ekspedycja',
        title: 'Zaginiona ekspedycja',
        category: 'Tajemnica', difficulty: 'Legendarny',
        discordChannel: '#gory-frostfang',
        reward: { points: 60, xp: 180, skirniry: 50, item: 'Dziennik Ekspedycji Frostfang' },
        description: 'Dziesięcioosobowa ekspedycja Durmstrangu zaginęła rok temu. Ostatnia wiadomość: "Jest coś żywego w szczelinie. Nie widzi nas. Jeszcze."',
        initialBotMessage: '⛰️ **[TMD BOT - KOPALNIA FROSTFANG · FINAŁ]**\nLatarnie eksplodowały. Ściany pokrywa lód od wewnątrz.\n*Z głębi: równomierne uderzenia. Coś liczące sekundy.*\n\nJak postępujesz:',
        suggestedActions: [
          { label: '🕯️ Zapal runiczny ogień i zejdź', cmd: '/swiatlo runiczny-ogien zejdz' },
          { label: '📻 Użyj zaklęcia Echo', cmd: '/rzut echo glosy-kopalnia' },
          { label: '🏃 Zbadaj szybko i wycofaj', cmd: '/szybkie-zbadanie wycofaj' },
        ],
        solutionKeywords: ['ogien', 'echo', 'glosy', 'kopalnia', 'ekspedycja', 'zbadaj'],
        successMessage: '✨ Dziennik ekspedycji zamrożony w bryle lodu. I coś innego — sylwetka poruszająca się zbyt wolno na żywą i zbyt regularnie na martwą.',
        failMessage: '❄️ Lód blokuje zejście. Potrzebujesz zaklęcia topnienia.',
      },
    ]),
  },

  {
    id: 'wl-frost-przelecz',
    name: 'Przełęcz Frostfang',
    nordic_name: 'Frostfangsskarð',
    x: 46, y: 24,
    icon: '🏔️', type: 'poi', region: 'Północ',
    marker_type: 'location', visibility: 'visible', state: 'locked',
    short_desc: 'Jedyna droga przez Góry Frostfang — strzeżona przez Gunnara',
    description_short: 'Wejście do Frostfang · próba wytrwałości',
    full_lore: 'Wąska szczelina w skałach. Latem jest przejściem. Zimą jest próbą. Gunnar strzeże jej od dziewięciu lat.',
    npcs: q(['Strażnik Przełęczy Gunnar']),
    actions: q(['Zdaj Próbę Wytrwałości', 'Zapytaj Gunnara o góry', 'Obejrzyj tablicę poległych']),
    discovery_reward_xp: 15, discovery_reward_skirniry: 8,
    quests: q([]),
  },

// ═══════════════════════════════════════════════════════════════════
//  FJORDGARD — Największa osada
// ═══════════════════════════════════════════════════════════════════

  {
    id: 'wl-fjordgard',
    name: 'Fjordgard',
    nordic_name: 'Fjörðgarðr',
    x: 44, y: 74,
    icon: '🏘️', type: 'settlement', region: 'Południe',
    marker_type: 'location', visibility: 'visible', state: 'available',
    short_desc: 'Największa osada w okolicy Twierdzy — centrum handlu i plotek',
    description_short: 'Tawerna · rynek · kuźnia · questy fabularne',
    full_lore: 'Rybacy, kowale i kupcy. Fjordgard ma pamięć długą jak zima. Coś się wydarzyło kilka miesięcy temu. Żaden mieszkaniec nie chce o tym mówić. Studnia jest zabarierowana. Jarl nie wychodzi z domu.',
    npcs: q(['Kowal Thorvald', 'Karczmarz Björn', 'Jarl Sigurdr (niedostępny)', 'Stara Inge']),
    actions: q(['Odwiedź tawernę', 'Idź do kuźni', 'Kup zioła', 'Dowiedz się o studni']),
    discovery_reward_xp: 12, discovery_reward_skirniry: 6,
    quests: q([
      {
        id: 'quest-fjordgard-studnia',
        title: 'Kto zatruł studnię?',
        category: 'Śledztwo', difficulty: 'Średni',
        discordChannel: '#fjordgard',
        reward: { points: 30, xp: 85, skirniry: 20 },
        description: 'Woda w głównej studni zmieniła kolor na ciemnoniebieski. Trzy koty padły. Nikt nie mówi co się stało.',
        initialBotMessage: '🏘️ **[TMD BOT - FJORDGARD]**\nStudnia otoczona plecionym ogrodzeniem. Woda niebieskawa i śmierdzi starą magią.\n*Stara Inge obserwuje cię z targu.*\n\nJak badasz studnię:',
        suggestedActions: [
          { label: '🔬 Pobierz próbkę i zbadaj', cmd: '/pobierz probka-wody zbadaj' },
          { label: '🗣️ Zapytaj Inge co wie', cmd: '/zapytaj inge studnia-tajemnica' },
          { label: '🔮 Rzuć Revelatio Aquae', cmd: '/rzut revelatio-aquae studnia' },
        ],
        solutionKeywords: ['probka', 'inge', 'revelatio', 'trucizna', 'studnia'],
        successMessage: '✨ Revelatio wskazuje na Glacies Veneni — zaklęcie zimowej trucizny. Oczy Inge powiedziały wszystko. To nie był wypadek.',
        failMessage: '❄️ Woda blokuje detekcję. Potrzebujesz mocniejszego zaklęcia.',
      },
      {
        id: 'quest-fjordgard-kowal',
        title: 'Dług kowala',
        category: 'NPC & Zlecenia', difficulty: 'Łatwy',
        discordChannel: '#fjordgard',
        reward: { points: 15, xp: 40, skirniry: 10, item: 'Runiczny Amulet Kowala' },
        description: 'Kowal Thorvald prosi o węgiel runiczny z kopalni Frostfang. W zamian — własnoręcznie wykuty amulet.',
        initialBotMessage: '⚒️ **[TMD BOT - KUŹNIA THORVALDA]**\nKowal wielki jak niedźwiedź kłada na stole kartkę.\n*„Węgiel runiczny. Z kopalni Frostfang. Nie z żadnego innego miejsca."*\n\nCo odpowiadasz:',
        suggestedActions: [
          { label: '✅ Przyjmij zlecenie', cmd: '/przyjmij zlecenie thorvald-wegiel' },
          { label: '❓ Zapytaj o powód', cmd: '/zapytaj thorvald powod-wegiel' },
          { label: '💰 Negocjuj zaliczkę', cmd: '/negocjuj thorvald zaliczka' },
        ],
        solutionKeywords: ['przyjmij', 'wegiel', 'thorvald', 'frostfang', 'runiczny'],
        successMessage: '✨ Thorvald wręcza ci ciepły jeszcze amulet. *„Runy są właściwe. Nie pytaj skąd wiem."*',
        failMessage: '❄️ Thorvald nie jest zainteresowany inną ofertą.',
      },
      {
        id: 'quest-fjordgard-duch-rybaka',
        title: 'Duch starego rybaka',
        category: 'Tajemnica', difficulty: 'Średni',
        discordChannel: '#fjordgard',
        reward: { points: 22, xp: 65, skirniry: 14 },
        description: 'Björn z tawerny twierdzi, że przy starej łodzi na dooku każdej nocy pojawia się postać. Sprzęt wędkarski układa się sam. Pozostawia mokre ślady.',
        initialBotMessage: '🍺 **[TMD BOT - PORT FJORDGARD]**\nStara łódź przy doku. Mokre ślady na deskach. Sieć ułożona dokładniej niż by ktokolwiek żywy to zrobił.\n\nJak badasz zjawisko:',
        suggestedActions: [
          { label: '👻 Przywołaj ducha — Invoca Spiritus', cmd: '/rzut invoca-spiritus dok' },
          { label: '👁️ Czekaj do północy', cmd: '/czekaj polnoc dok-fjordgard' },
          { label: '📜 Zbadaj historię łodzi', cmd: '/zbadaj lodz historia-fjordgard' },
        ],
        solutionKeywords: ['duch', 'invoca', 'spiritus', 'dok', 'polnoc', 'lodz', 'historia'],
        successMessage: '✨ Duch starego Ulfara materializuje się. Nie jest agresywny — szuka swojej sieci, którą ktoś zabrał z portu tydzień przed jego śmiercią. Odda ją kiedy znajdziesz złodzieja.',
        failMessage: '❄️ Duch nie pojawia się. Wróć o północy.',
      },
    ]),
  },

  {
    id: 'wl-fjordgard-tawerna',
    name: 'Tawerna „Pod Złamanym Rogiem"',
    nordic_name: 'Brotinn Horn Kró',
    x: 40, y: 76,
    icon: '🍺', type: 'settlement', region: 'Południe',
    marker_type: 'npc', visibility: 'visible', state: 'available',
    short_desc: 'Jedyne miejsce gdzie można zdobyć informacje i gorącą zupę',
    description_short: 'NPC: Björn · plotki · zlecenia · nocleg',
    full_lore: 'Złamany Róg wisi nad barem od dwustu lat. Björn nie zdejmuje go. Nie dlatego, że wierzy w legendę — ale żeby nie sprawdzać.',
    npcs: q(['Karczmarz Björn', 'Stali bywalcy']),
    actions: q(['Zjedz kolację', 'Kup informacje', 'Posłuchaj plotek', 'Zostań na noc']),
    discovery_reward_xp: 8, discovery_reward_skirniry: 4,
    quests: q([
      {
        id: 'quest-tawerna-kradzione-sny',
        title: 'Skradzione sny',
        category: 'Tajemnica', difficulty: 'Łatwy',
        discordChannel: '#fjordgard',
        reward: { points: 12, xp: 30, skirniry: 8 },
        description: 'Björn twierdzi, że ktoś okrada gości ze snu — dosłownie. Budzą się bez wspomnień z poprzedniej nocy.',
        initialBotMessage: '🍺 **[TMD BOT - TAWERNA POD ZŁAMANYM ROGIEM]**\nBjörn ścisza głos. *„Trzecia noc z rzędu. Ten sam gość — rano nic nie pamięta."*\n\nJak badasz sprawę:',
        suggestedActions: [
          { label: '👁️ Zostań na noc i obserwuj', cmd: '/zostan noc obserwacja-potajemna' },
          { label: '🔮 Sprawdź pokój na magię', cmd: '/rzut detekcja magia-pokoj' },
          { label: '💊 Pobierz próbkę jedzenia', cmd: '/pobierz probka-jedzenia analiza' },
        ],
        solutionKeywords: ['obserwacja', 'magia', 'pokoj', 'detekcja', 'jedzenie', 'sen'],
        successMessage: '✨ W pokoju: runiczna pułapka snu przyczepiona pod łóżkiem. Ktoś kradnie sny — i musi je gdzieś przechowywać.',
        failMessage: '❄️ Nic podejrzanego. Może następnej nocy.',
      },
    ]),
  },

// ═══════════════════════════════════════════════════════════════════
//  HAVNHOLD — Mroczna osada
// ═══════════════════════════════════════════════════════════════════

  {
    id: 'wl-havnhold',
    name: 'Havnhold',
    nordic_name: 'Hafnholdr',
    x: 30, y: 30,
    icon: '🏚️', type: 'settlement', region: 'Północny Zachód',
    marker_type: 'location', visibility: 'visible', state: 'available',
    short_desc: 'Odizolowana osada górska — coś tu jest bardzo nie tak',
    description_short: 'Quest chain: Tajemnica Havnhold (6 części)',
    full_lore: 'Mała osada, do której droga wiedzie przez wąski jar. Mieszkańcy mało mówią. Dużo milczą. Studnia zabarierowana od zimy. Spalony dom stoi nieodbudowany od miesięcy. Nikt nie pyta dlaczego.',
    npcs: q(['Starszyzna Orm', 'Karczmarka Gudrun', 'Niemówiące dziecko']),
    actions: q(['Wejdź do karczmy', 'Spróbuj porozmawiać', 'Zbadaj studnię', 'Sprawdź spalony dom']),
    discovery_reward_xp: 18, discovery_reward_skirniry: 10,
    quests: q([
      {
        id: 'quest-havnhold-1',
        title: 'Droga do Havnhold',
        category: 'Quest Chain — Havnhold', difficulty: 'Łatwy',
        discordChannel: '#havnhold-tajemnica',
        reward: { points: 12, xp: 35, skirniry: 6 },
        description: 'CZĘŚĆ 1/6: Dotarcie do odizolowanej osady. Droga przez wąski jar jest trudna — i ktoś wyraźnie nie dba o jej utrzymanie.',
        initialBotMessage: '🏚️ **[TMD BOT - DROGA DO HAVNHOLD]**\nJar jest wąski. Kamienie na drodze ułożone jakby ktoś je tu specjalnie położył.\n*Za zakrętem: dym z kominów. Ale cicho.*\n\nJak docierasz do osady:',
        suggestedActions: [
          { label: '🚶 Idź bezpośrednio przez jar', cmd: '/przejdz jar-havnhold' },
          { label: '🔍 Zbadaj układ kamieni', cmd: '/zbadaj kamienie-jar' },
          { label: '🌲 Obejdź dookoła przez las', cmd: '/obejdz las-havnhold' },
        ],
        solutionKeywords: ['jar', 'kamienie', 'przejdz', 'havnhold', 'droga'],
        successMessage: '✨ Wchodzisz do Havnhold. Kilkoro mieszkańców patrzy na ciebie — i odwraca wzrok zanim zdążysz ich pozdrowić.',
        failMessage: '❄️ Droga jest zablokowana. Poszukaj innej trasy.',
      },
      {
        id: 'quest-havnhold-2',
        title: 'Milczący mieszkańcy',
        category: 'Quest Chain — Havnhold', difficulty: 'Trudny',
        discordChannel: '#havnhold-tajemnica',
        reward: { points: 25, xp: 75, skirniry: 18 },
        description: 'CZĘŚĆ 2/6: Mieszkańcy odpowiadają jednosłowowo lub wcale. Dziecko stoi przy studni. Od tygodnia.',
        initialBotMessage: '🏚️ **[TMD BOT - HAVNHOLD]**\nKarczma pusta choć środek dnia. Gudrun nalewa bez pytania.\nDziecko przy studni patrzy w wodę.\n*Cisza, która boli.*\n\nCo robisz:',
        suggestedActions: [
          { label: '👧 Podejdź do dziecka', cmd: '/podejdz dziecko studnia' },
          { label: '🗣️ Spróbuj z Gudrun', cmd: '/rozmowa gudrun havnhold' },
          { label: '🔍 Zbadaj pustą karczmę', cmd: '/zbadaj karczma havnhold' },
        ],
        solutionKeywords: ['dziecko', 'studnia', 'gudrun', 'karczma'],
        successMessage: '✨ Dziecko obraca się. Na nadgarstku — runa Isa wyryta w skórze. Świeża. Gudrun: *„Wyjdź. Zanim zostaniesz."*',
        failMessage: '❄️ Nikt nie odpowiada.',
      },
      {
        id: 'quest-havnhold-4',
        title: 'Studnia',
        category: 'Quest Chain — Havnhold', difficulty: 'Trudny',
        discordChannel: '#havnhold-tajemnica',
        reward: { points: 30, xp: 90, skirniry: 22 },
        description: 'CZĘŚĆ 4/6: Studnia jest głównym punktem osady. Zbadaj ją, zanim ktoś cię zatrzyma.',
        initialBotMessage: '🏚️ **[TMD BOT - STUDNIA HAVNHOLD]**\nWoda jest czarna. Na dnie refleks księżyca — choć jest południe.\n*Dziecko stoi za tobą i nie mówi nic.*\n\nJak badasz studnię:',
        suggestedActions: [
          { label: '💧 Pobierz wodę i zbadaj', cmd: '/pobierz woda-studnia zbadaj' },
          { label: '🔮 Rzuć Profunditas', cmd: '/rzut profunditas studnia' },
          { label: '🪣 Opuść wiadro', cmd: '/opusc wiadro studnia-dno' },
        ],
        solutionKeywords: ['woda', 'studnia', 'profunditas', 'dno', 'wiadro'],
        successMessage: '✨ Profunditas: studnia ma siedem metrów. Ale na dnie siedzi coś, co ma temperaturę ciała. I nie jest wodą.',
        failMessage: '❄️ Magia odpycha. Studnia zapieczętowana od środka.',
      },
      {
        id: 'quest-havnhold-final',
        title: 'Havnhold',
        category: 'Quest Chain — Havnhold', difficulty: 'Legendarny',
        discordChannel: '#havnhold-tajemnica',
        reward: { points: 70, xp: 210, skirniry: 55, item: 'Klucz do Studni Havnhold' },
        description: 'FINAŁ 6/6: Po przejściu przez cały chain wiesz co jest w studni. Pytanie: co z tym zrobisz?',
        initialBotMessage: '🏚️ **[TMD BOT - HAVNHOLD · FINAŁ]**\nKlucz do studni jest w twojej ręce. Mieszkańcy obserwują zza okien.\n*Dziecko kiwa głową.*\n*Gudrun otwiera drzwi karczmy szerzej.*\n\nCo robisz:',
        suggestedActions: [
          { label: '🔓 Otwórz studnię i zmierz się z tym co w środku', cmd: '/otworz studnia-havnhold konfront' },
          { label: '📜 Wróć do Twierdzy z raportem', cmd: '/raport twierdza-havnhold' },
          { label: '🤫 Zapieczętuj studnię i milcz', cmd: '/zapieczet studnia powrot' },
        ],
        solutionKeywords: ['studnia', 'otworz', 'raport', 'zapieczet', 'konfront', 'klucz'],
        successMessage: '✨ Twój wybór zmienia los Havnhold. Każda z trzech dróg prowadzi do innych konsekwencji — i do różnych questów w Twierdzy. Osada jest wolna. Albo bezpieczna. Albo zapomniana.',
        failMessage: '❄️ Studnia opiera się. Potrzebujesz klucza z poprzednich części chaina.',
      },
    ]),
  },

// ═══════════════════════════════════════════════════════════════════
//  RUNEHAVEN — Dolina Run
// ═══════════════════════════════════════════════════════════════════

  {
    id: 'wl-runehaven',
    name: 'Runehaven',
    nordic_name: 'Rúnaheimr',
    x: 74, y: 46,
    icon: '🗿', type: 'region', region: 'Wschód',
    marker_type: 'location', visibility: 'visible', state: 'available',
    short_desc: 'Dolina starożytnych kamieni runicznych — serce wiedzy Północy',
    description_short: 'Zagadki runiczne · chain · starożytna wiedza',
    full_lore: 'Kamienny krąg i monolity sprzed tysięcy lat. Runy wyrzeźbione w nieznanym dialekcie. Prof. Starożytnych Run twierdzi, że zna połowę. Druga połowa jest gdzie indziej.',
    npcs: q(['Duch Runmistrza Algira', 'Milczący Monolit']),
    actions: q(['Przepisuj inskrypcje', 'Aktywuj monolit', 'Szukaj grobowców']),
    discovery_reward_xp: 18, discovery_reward_skirniry: 10,
    quests: q([
      {
        id: 'quest-rune-algiz',
        title: 'Kamień Algiz',
        category: 'Starożytne Runy', difficulty: 'Średni',
        discordChannel: '#runehaven',
        reward: { points: 25, xp: 70, skirniry: 15, item: 'Odczyt Algiz — fragment 2/4' },
        description: 'Monolit Algiz reaguje na odpowiednie zaklęcia runiczne. Musisz znaleźć właściwą kombinację.',
        initialBotMessage: '🗿 **[TMD BOT - MONOLIT ALGIZ]**\nKamień ma cztery metry. Na powierzchni: dwadzieścia run. Na dole: puste miejsce na jedną.\n\n*Którą runę dokładasz:*',
        suggestedActions: [
          { label: 'ᛉ Algiz — runa ochrony', cmd: '/aktywuj runa-algiz monolit' },
          { label: 'ᛏ Tiwaz — runa sprawiedliwości', cmd: '/aktywuj runa-tiwaz monolit' },
          { label: '📜 Skonsultuj bibliotekę', cmd: '/biblioteka runehaven-klucz' },
        ],
        solutionKeywords: ['algiz', 'runa', 'monolit', 'aktywuj', 'biblioteka'],
        successMessage: '✨ Monolit rozświetla się błękitnie. Wysuwa kamienna płytka — drugi fragment z czterech do Imienia Runmistrza.',
        failMessage: '❄️ Błędna runa. Kamień odpycha energię.',
      },
      {
        id: 'quest-rune-dziewiec',
        title: 'Dziewięć znaków',
        category: 'Starożytne Runy', difficulty: 'Średni',
        discordChannel: '#runehaven',
        reward: { points: 20, xp: 60, skirniry: 15 },
        description: 'Ołtarz Dziewięciu Znaków wymaga aktywacji w odpowiedniej kolejności zakodowanej w inskrypcjach.',
        initialBotMessage: '🗿 **[TMD BOT - OŁTARZ DZIEWIĘCIU ZNAKÓW]**\nDziewięć kamiennych płyt. Na środku: otwór na różdżkę.\n*Kolejność aktywacji musi być precyzyjna.*\n\nJak szukasz kolejności:',
        suggestedActions: [
          { label: '📖 Odczytaj inskrypcje na monolitach', cmd: '/odczytaj inskrypcje runehaven-kolejnosc' },
          { label: '📚 Wróć do biblioteki', cmd: '/biblioteka kolejnosc-oltarz' },
          { label: '🔮 Wykryj aktywne połączenia', cmd: '/rzut detekcja runiczne-polaczenia' },
        ],
        solutionKeywords: ['kolejnosc', 'oltarz', 'inskrypcja', 'aktywuj', 'dziewiec'],
        successMessage: '✨ Fehu, Uruz, Thurisaz, Ansuz, Raido, Kenaz, Gebo, Wunjo, Hagalaz. Spod ziemi wysuwa się mapa Runehaven.',
        failMessage: '❄️ Błędna kolejność. Ołtarz resetuje się.',
      },
      {
        id: 'quest-rune-grobowiec',
        title: 'Grobowiec Runmistrza',
        category: 'Quest Chain — Runehaven', difficulty: 'Trudny',
        discordChannel: '#runehaven',
        reward: { points: 50, xp: 150, skirniry: 40, item: 'Kompletna Inskrypcja Runmistrza' },
        description: 'FINAŁ: Po zebraniu wszystkich czterech fragmentów wchodzisz do grobowca. Duch Algira nie umarł — jest uwięziony.',
        initialBotMessage: '🗿 **[TMD BOT - GROBOWIEC RUNMISTRZA · FINAŁ]**\nDuch Algira materializuje się — gęstszy niż zwykłe widmo.\n*„Kto odczytał moje imię — wchodzi."*\n\nJak się przedstawiasz:',
        suggestedActions: [
          { label: '📜 Wypowiedz Imię Runmistrza', cmd: '/wypowiedz imie-runmistrza algir' },
          { label: '🙏 Oddaj hołd w starym dialekcie', cmd: '/hold stary-dialekt runmistrz' },
          { label: '🤝 Zaproponuj wymianę wiedzy', cmd: '/wymiana wiedza runmistrz' },
        ],
        solutionKeywords: ['imie', 'algir', 'runmistrz', 'hold', 'wymiana', 'dialekt'],
        successMessage: '✨ Algir: *„Dawno nikt nie przyszedł z imieniem."* Przekazuje mapę do Źródła Mímira i ostrzeżenie przed Trzynastym Kamieniem.',
        failMessage: '❄️ Duch Algira milknie. Wróć z pełną inskrypcją.',
      },
    ]),
  },

  {
    id: 'wl-rune-krag',
    name: 'Runiczny Krąg',
    nordic_name: 'Rúnhringr',
    x: 70, y: 42,
    icon: '🗿', type: 'ruins', region: 'Wschód',
    marker_type: 'quest', visibility: 'visible', state: 'available',
    short_desc: 'Główny krąg Runehaven — centrum energii Doliny',
    description_short: 'Zagadki · aktywacja węzłów runicznych',
    full_lore: 'Dwanaście kamieni w kręgu, dwanaście run. Jeden kamień pusty — czternasty. Matematyka tu nie działa jak powinna.',
    npcs: q([]),
    actions: q(['Aktywuj kamienie', 'Zmierz kąty', 'Szukaj trzynastego miejsca']),
    discovery_reward_xp: 15, discovery_reward_skirniry: 8,
    quests: q([]),
  },

  {
    id: 'wl-rune-grobowiec',
    name: 'Grobowiec Runmistrza',
    nordic_name: 'Rúnameistaragröf',
    x: 77, y: 50,
    icon: '⚰️', type: 'ruins', region: 'Wschód',
    marker_type: 'secret', visibility: 'visible', state: 'locked',
    short_desc: 'Zamknięty grobowiec — otwiera się po zebraniu 4 fragmentów inskrypcji',
    description_short: 'Finał chain Runehaven · odblokowany po 4/4 fragmentach',
    full_lore: 'Wejście bez klamki. Wejście bez zawiasów. Wejście, które wygląda jak ściana — dopóki nie wiesz czego szukać.',
    npcs: q(['Duch Runmistrza Algira']),
    actions: q(['Połóż 4 fragmenty na ołtarzu', 'Wejdź do grobowca', 'Porozmawiaj z Algirem']),
    discovery_reward_xp: 25, discovery_reward_skirniry: 15,
    quests: q([]),
  },

// ═══════════════════════════════════════════════════════════════════
//  CMENTARZ VARGHEIM
// ═══════════════════════════════════════════════════════════════════

  {
    id: 'wl-vargheim',
    name: 'Cmentarz Vargheim',
    nordic_name: 'Vargheimr',
    x: 37, y: 62,
    icon: '🪦', type: 'region', region: 'Zachód',
    marker_type: 'location', visibility: 'visible', state: 'available',
    short_desc: 'Ukryty cmentarz rodu Varg — nie wszystkie groby są zamknięte',
    description_short: 'Tajemnica · krypta · questy śmierci',
    full_lore: 'Stary cmentarz rodu Varg. Ostatni zapis w księdze cmentarnej: sześćdziesiąt lat temu. Ale groby są nowe.',
    npcs: q(['Duch Bezimiennego', 'Strażnik Kurhanu']),
    actions: q(['Przejdź Bramę Umarłych', 'Zbadaj kryptę', 'Odczytaj nagrobki', 'Zbadaj kurhan']),
    discovery_reward_xp: 16, discovery_reward_skirniry: 9,
    quests: q([
      {
        id: 'quest-varg-groby',
        title: 'Nie wszystkie groby są zamknięte',
        category: 'Tajemnica', difficulty: 'Trudny',
        discordChannel: '#vargheim',
        reward: { points: 35, xp: 100, skirniry: 25 },
        description: 'Jeden nagrobek ma świeże kwiaty. Data śmierci: 300 lat temu. Ktoś tu regularnie przychodzi — albo ten ktoś sam to robi.',
        initialBotMessage: '🪦 **[TMD BOT - CMENTARZ VARGHEIM]**\nJeden grób ma świeże kwiaty i ciepłą ziemię.\n*„Ktoś tu był dziś rano."*\n\nJak badasz grób:',
        suggestedActions: [
          { label: '🔍 Zbadaj ślady', cmd: '/zbadaj slady-nagrobek varg' },
          { label: '👻 Przywołaj ducha — Invoca Mortem', cmd: '/rzut invoca-mortem nagrobek' },
          { label: '🌸 Zbadaj kwiaty', cmd: '/zbadaj kwiaty nagrobek' },
        ],
        solutionKeywords: ['slady', 'invoca', 'duch', 'kwiaty', 'grob', 'varg'],
        successMessage: '✨ Grobowiec jest portalem. Ktoś otwierał go dziś rano z drugiej strony.',
        failMessage: '❄️ Ziemia odpycha magię. Grób zapieczętowany od środka.',
      },
      {
        id: 'quest-varg-pierscien',
        title: 'Pierścień Varga',
        category: 'Artefakty', difficulty: 'Średni',
        discordChannel: '#vargheim',
        reward: { points: 25, xp: 70, skirniry: 18, item: 'Pierścień Rodu Varg' },
        description: 'Pierścień rodu Varg, skradziony sto lat temu, jest ukryty w krypcie. Karczmarz z Fjordgardu twierdzi że wie komu go zwrócić.',
        initialBotMessage: '🪦 **[TMD BOT - STARA KRYPTA]**\nNa środku: kamienna płyta z herbem rodu Varg — wilk wyjący na księżyc.\n*Pod płytą coś pulsuje regularnie.*\n\nJak szukasz pierścienia:',
        suggestedActions: [
          { label: '🔓 Przesuń płytę — Mobilius', cmd: '/rzut mobilius plyta-krypta' },
          { label: '🔍 Zbadaj herby na ścianach', cmd: '/zbadaj herby krypta-varg' },
          { label: '🧩 Szukaj mechanizmu', cmd: '/szukaj mechanizm krypta' },
        ],
        solutionKeywords: ['mobilius', 'plyta', 'herb', 'krypta', 'pierscien', 'varg'],
        successMessage: '✨ Pod płytą pierścień — ale na wierzchu kartka: *„Czekałem aż ktoś go znajdzie. Teraz wiemy, że ktoś szuka."*',
        failMessage: '❄️ Płyta zapieczętowana. Potrzebujesz właściwego zaklęcia.',
      },
    ]),
  },

// ═══════════════════════════════════════════════════════════════════
//  RUINY SKALLGARD
// ═══════════════════════════════════════════════════════════════════

  {
    id: 'wl-skallgard',
    name: 'Ruiny Skallgard',
    nordic_name: 'Skallgarðr',
    x: 61, y: 34,
    icon: '🏛️', type: 'ruins', region: 'Północny Wschód',
    marker_type: 'location', visibility: 'visible', state: 'available',
    short_desc: 'Pozostałości placówki starszej od Durmstrangu — główna tajemnica świata',
    description_short: 'Główny quest chain TMD · Durmstrang nie był pierwszy',
    full_lore: 'Ruiny sprzed Durmstrangu. Oficjalna wersja: stara osada. Nieoficjalna: szkoła magiczna działająca dwieście lat przed Twierdzą — która zniknęła bez śladu. Nie ma kronik. Nie ma absolwentów. Jest kamień z herbem, którego nikt nie rozpoznaje.',
    npcs: q(['Archeolog Björk', 'Coś w Podziemnym Archiwum']),
    actions: q(['Eksploruj ruiny', 'Zbadaj herb', 'Znajdź Archiwum', 'Zapisz inskrypcje']),
    discovery_reward_xp: 22, discovery_reward_skirniry: 14,
    quests: q([
      {
        id: 'quest-skall-kamienie',
        title: 'Kamienie Skallgardu',
        category: 'Quest Chain — Skallgard', difficulty: 'Łatwy',
        discordChannel: '#skallgard',
        reward: { points: 15, xp: 40, skirniry: 8 },
        description: 'CZĘŚĆ 1/6: Pierwsze zbadanie ruin. Teren jest niestabilny — i wydaje się że to nie tylko kwestia wieku.',
        initialBotMessage: '🏛️ **[TMD BOT - RUINY SKALLGARD]**\nMury stoją mimo setek lat. Zbyt dobrze jak na naturalne ruiny.\n*Kamienie są ułożone w pewien wzór. Wzór, który mógł być celowy.*\n\nJak eksperymujesz:',
        suggestedActions: [
          { label: '🗺️ Zmapuj układ murów', cmd: '/mapuj ruiny-skallgard uklad' },
          { label: '🔮 Wykryj resztki magii', cmd: '/rzut detekcja magia-ruiny' },
          { label: '⛏️ Sprawdź fundament', cmd: '/zbadaj fundament skallgard' },
        ],
        solutionKeywords: ['mapuj', 'detekcja', 'fundament', 'ruiny', 'skallgard', 'wzor'],
        successMessage: '✨ Ruiny nie opadły przypadkowo. Wzór ich upadku wskazuje na eksplosję od środka — od bardzo dawna, ale świadomą.',
        failMessage: '❄️ Teren jest zbyt niestabilny. Ostrożniej.',
      },
      {
        id: 'quest-skall-herb',
        title: 'Nieznany herb',
        category: 'Quest Chain — Skallgard', difficulty: 'Średni',
        discordChannel: '#skallgard',
        reward: { points: 25, xp: 70, skirniry: 16 },
        description: 'CZĘŚĆ 2/6: Herb na głównym kamieniu — czarny orzeł na złotym tle z łacińskim napisem. Ani biblioteka Durmstrangu, ani Runehaven nie mają wzmianek.',
        initialBotMessage: '🏛️ **[TMD BOT - KAMIEŃ Z HERBEM]**\nHerb jest wyraźny — jakby wyryty wczoraj, nie dwieście lat temu.\n*„Quis custodiet."*\nTo łacina. Tu, na Północy.\n\nJak badasz herb:',
        suggestedActions: [
          { label: '📸 Narysuj herb i zbadaj heraldycznie', cmd: '/heraldyka herb-skallgard analiza' },
          { label: '📖 Przetłumacz łaciński napis', cmd: '/tlumacz lacina herb-napis' },
          { label: '🔮 Wykryj magię w kamieniu', cmd: '/rzut detekcja kamien-herb' },
        ],
        solutionKeywords: ['herb', 'lacina', 'skallgard', 'quis', 'tlumacz', 'heraldyka'],
        successMessage: '✨ *„Kto pilnuje strażników."* Herb pasuje do grobowca w Runehaven — czarny orzeł na nagrobku, który Algir milcząco omijał.',
        failMessage: '❄️ Herb zbyt zatarty lub detekcja zakłócona.',
      },
      {
        id: 'quest-skall-historia',
        title: 'Historia, której nie uczą',
        category: 'Quest Chain — Skallgard', difficulty: 'Legendarny',
        discordChannel: '#skallgard',
        reward: { points: 80, xp: 250, skirniry: 70, item: 'Kronika Pierwszej Szkoły' },
        description: 'FINAŁ 6/6: Archiwum otwarte. Kroniki placówki przed Durmstrangiem. I odpowiedź: dlaczego Durmstrang zbudowano dokładnie na jej gruzach.',
        initialBotMessage: '🏛️ **[TMD BOT - PODZIEMNE ARCHIWUM · FINAŁ]**\nDrzwi się otwierają. W środku ciemno — ale nie cicho.\n*Coś tu jest żywe od dwustu lat.*\n*„Kto pytasz?"*\n\nJak odpowiadasz Strażnikowi:',
        suggestedActions: [
          { label: '📜 Cytuj kroniki które już znasz', cmd: '/cytuj kroniki-skallgard straznik' },
          { label: '❓ Zapytaj o prawdziwą historię', cmd: '/zapytaj straznik-archiwum historia' },
          { label: '🤝 Zaproponuj rozpowszechnienie wiedzy', cmd: '/propozycja rozpowszechnienie-kronik' },
        ],
        solutionKeywords: ['kroniki', 'historia', 'straznik', 'archiwum', 'prawda'],
        successMessage: '✨ *„Durmstrang zbudował się na ruinach szkoły, którą zniszczył. Z powodu strachu — nie zła. Bali się tego, czego tamci się dowiedzieli."* Dostajesz Kronikę. Pytanie pierwsze: co odkryli poprzednicy?',
        failMessage: '❄️ Strażnik nie jest przekonany. Wróć z pełną wiedzą o Skallgardzie.',
      },
    ]),
  },

  {
    id: 'wl-skall-archiwum',
    name: 'Podziemne Archiwum Skallgard',
    nordic_name: 'Undirjörðar Skjaldarshof',
    x: 64, y: 37,
    icon: '📜', type: 'ruins', region: 'Północny Wschód',
    marker_type: 'secret', visibility: 'visible', state: 'locked',
    short_desc: 'Ukryte archiwum pod ruinami — zamknięte do czasu odkrycia herbu',
    description_short: 'Sekret · odblokowane po chain Skallgard',
    full_lore: 'Wejście jest niewidoczne dla tych, którzy nie wiedzą czego szukać. Kamień, który świeci się przy pełni. Archiwum adaptuje się do osoby, która wchodzi.',
    npcs: q(['Strażnik Archiwum (byt magiczny)']),
    actions: q(['Odczytaj kroniki', 'Zrób kopię inskrypcji', 'Zapytaj Strażnika']),
    discovery_reward_xp: 30, discovery_reward_skirniry: 20,
    quests: q([]),
  },

// ═══════════════════════════════════════════════════════════════════
//  FJORMHARD — Port Północy
// ═══════════════════════════════════════════════════════════════════

  {
    id: 'wl-fjormhard',
    name: 'Fjormhard',
    nordic_name: 'Fjörðharðr',
    x: 80, y: 66,
    icon: '⚓', type: 'settlement', region: 'Wschód',
    marker_type: 'location', visibility: 'visible', state: 'locked',
    short_desc: 'Brutalny port Północy — przemytnicy, czarny rynek, sekrety',
    description_short: 'Zablokowany · port z wyborami moralnymi',
    full_lore: 'Port, do którego przybijają statki z całej Północy. Nie wszystkie z czystym towarem. Kapitanat wie i milczy. Władze Twierdzy wiedzą i patrzą w inną stronę. Do czasu.',
    npcs: q(['Kapitan Leifr (zaginiony)', 'Przemytnik Snorri', 'Celnik Halvar']),
    actions: q(['Poszukaj kapitana', 'Zbadaj doki nocą', 'Odwiedź czarny rynek']),
    discovery_reward_xp: 20, discovery_reward_skirniry: 12,
    quests: q([
      {
        id: 'quest-fjorm-przemytnicy',
        title: 'Towar bez właściciela',
        category: 'Wybory Moralne', difficulty: 'Trudny',
        discordChannel: '#fjormhard',
        reward: { points: 35, xp: 100, skirniry: 25, item: 'Artefakt Północy (wariant zależny od wyboru)' },
        description: 'W opuszczonym magazynie znaleziono skrzynię bez właściciela. Celnik Halvar chce połowę. Snorri twierdzi, że to jego. Skrzynia sama decyduje kto ją otwiera.',
        initialBotMessage: '⚓ **[TMD BOT - FJORMHARD · DOK PRZEMYTNIKÓW]**\nSkrzynia ciepła mimo mrozu. Zamek ma trzy runy.\n*Halvar krąży. Snorri czeka. Ty trzymasz zamek.*\n\nCo robisz ze skrzynią:',
        suggestedActions: [
          { label: '🏛️ Oddaj władzom Twierdzy', cmd: '/oddaj skrzynia wladze-twierdzy' },
          { label: '🏴‍☠️ Pomóż Snorriemu otworzyć', cmd: '/pomoz snorri skrzynia' },
          { label: '🎒 Zatrzymaj artefakt dla siebie', cmd: '/zachowaj artefakt osobiscie' },
        ],
        solutionKeywords: ['skrzynia', 'artefakt', 'snorri', 'halvar', 'oddaj', 'zachowaj'],
        successMessage: '✨ Twój wybór ma konsekwencje — każda z trzech dróg prowadzi do innego artefaktu i questów. Nie ma złej odpowiedzi. Ale nie ma powrotu.',
        failMessage: '❄️ Skrzynia zamknęła się. Poczekaj godzinę.',
      },
      {
        id: 'quest-fjorm-statek-widmo',
        title: 'Statek widmo',
        category: 'Tajemnica', difficulty: 'Trudny',
        discordChannel: '#fjormhard',
        reward: { points: 30, xp: 90, skirniry: 22 },
        description: 'Każdej nocy o trzeciej do portu przybija statek. Cumuje. O czwartej odpływa. Nikt go nie widział w dzień. Nikt nie zna jego nazwy.',
        initialBotMessage: '⚓ **[TMD BOT - FJORMHARD · NOC]**\nTrzecia w nocy. Na horyzoncie: sylwetka statku bez świateł.\n*Cumuje bez dźwięku. Nikt nie wysiada. Nikt nie wsiada.*\n\nCo robisz:',
        suggestedActions: [
          { label: '🚣 Podpłyń do statku', cmd: '/podplyw statek-widmo fjormhard' },
          { label: '📡 Rzuć zaklęcie Echo', cmd: '/rzut echo statek-widmo' },
          { label: '👁️ Obserwuj z bezpiecznej odległości', cmd: '/obserwuj statek-widmo port' },
        ],
        solutionKeywords: ['statek', 'widmo', 'echo', 'podplyw', 'obserwuj'],
        successMessage: '✨ Bliżej — statek nosi imię: *Hrimfaxi*. Ten sam wrak, który leży na dnie Zamarzniętego Fiordu od siedemdziesięciu lat. Oba są prawdziwe.',
        failMessage: '❄️ Statek odpływa przed świtem. Wróć o trzeciej.',
      },
    ]),
  },

// ═══════════════════════════════════════════════════════════════════
//  MORZE KRAKENA
// ═══════════════════════════════════════════════════════════════════

  {
    id: 'wl-kraken-sea',
    name: 'Morze Krakena',
    nordic_name: 'Krákusjár',
    x: 85, y: 20,
    icon: '🌊', type: 'region', region: 'Morze',
    marker_type: 'location', visibility: 'hidden', state: 'locked',
    short_desc: 'Otwarte wody Dalekiej Północy — ekspedycje morskie',
    description_short: 'Ukryte · ekspedycje morskie o wysokim ryzyku',
    full_lore: 'Nikt nie wraca z Morza Krakena z pełną załogą. Wrak Naglfara stoi na mieliźnie od stu lat — z jego kadłuba nocami wychodzi światło.',
    npcs: q(['Kapitan Bez Twarzy (legenda)']),
    actions: q(['Wyprawa na Morze Krakena', 'Zbadaj Wrak Naglfara', 'Szukaj Wyspy Mgły']),
    discovery_reward_xp: 40, discovery_reward_skirniry: 25,
    quests: q([
      {
        id: 'quest-kraken-naglfar',
        title: 'Naglfar',
        category: 'Ekspedycja Morska', difficulty: 'Legendarny',
        discordChannel: '#morze-krakena',
        reward: { points: 80, xp: 250, skirniry: 60, item: 'Kompas Naglfara' },
        description: 'Wrak Naglfar — wg legend nordyckich statek apokalipsy. Ten wrak na Morzu Krakena jest prawdziwy. I jest zajęty.',
        initialBotMessage: '🌊 **[TMD BOT - WRAK NAGLFARA]**\nŁódź zatrzymuje się sama. Wrak sięga czterdziestu metrów. Z luk: niebieskie światło.\n*Z wody: pomruk. Rytmiczny. Jak bicie serca.*\n\nJak podchodzisz:',
        suggestedActions: [
          { label: '⚓ Przybij do burty', cmd: '/prybij burta-naglfar' },
          { label: '🌊 Zanurz się pod kadłub', cmd: '/zanurz kadlub-naglfar' },
          { label: '📡 Obserwuj z odległości', cmd: '/obserwuj naglfar-z-odleglosci' },
        ],
        solutionKeywords: ['naglfar', 'burta', 'zanurz', 'kadlub', 'wrak'],
        successMessage: '✨ Wewnątrz: biblioteka. Tysiące ksiąg w języku który nie powinien istnieć. I jeden fotel przy oknie. Ciepły.',
        failMessage: '❄️ Coś pod wodą odpycha łódź. Wróć z mocniejszą ochroną.',
      },
    ]),
  },

// ═══════════════════════════════════════════════════════════════════
//  12 KAMIENI RUNICZNYCH — Meta-tajemnica mapy
// ═══════════════════════════════════════════════════════════════════

  ...[
    { n: 1,  x: 33, y: 54, rune: 'ᚠ', name: 'Fehu',    lore: 'Przy starej ścieżce między Jötunskógiem a Vargheim. Kamień jest ciepły, choć nie powinien być.' },
    { n: 2,  x: 22, y: 38, rune: 'ᚢ', name: 'Uruz',    lore: 'Pół ukryty pod mchem przy Rozdrozu Wisielców. Wygląda jak zwykły głaz, ale świeci przy pełni.' },
    { n: 3,  x: 57, y: 60, rune: 'ᚦ', name: 'Thurisaz', lore: 'Wystaje z lodu przy granicy Zamarzniętego Fiordu. Pięć metrów od brzegu.' },
    { n: 4,  x: 69, y: 44, rune: 'ᚨ', name: 'Ansuz',   lore: 'Stoi samotnie na wzgórzu przy Runehaven. Wszyscy go omijają bez wiadomo dlaczego.' },
    { n: 5,  x: 47, y: 27, rune: 'ᚱ', name: 'Raido',   lore: 'Na zboczu Frostfang tuż przed Przełęczą. Widoczny tylko z określonego kąta.' },
    { n: 6,  x: 75, y: 63, rune: 'ᚲ', name: 'Kenaz',   lore: 'Na molo w Fjormhardzie. Wygląda jak ozdoba — ale runa jest za stara na ozdobę.' },
    { n: 7,  x: 39, y: 41, rune: 'ᚷ', name: 'Gebo',    lore: 'Ukryty w lesie między Jötunskógiem a Havnhold. W jego pobliżu kompasy przestają działać.' },
    { n: 8,  x: 63, y: 25, rune: 'ᚹ', name: 'Wunjo',   lore: 'Na szczycie wzgórza przy Skallgardzie. Widok stąd obejmuje pół mapy.' },
    { n: 9,  x: 28, y: 69, rune: 'ᚺ', name: 'Hagalaz', lore: 'Częściowo zatopiony w bagnach przy Fjordgard. Dostępny tylko zimą gdy bagno zamarza.' },
    { n: 10, x: 82, y: 50, rune: 'ᚾ', name: 'Nauthiz',  lore: 'Na wschodnim wybrzeżu pół drogi do Fjormharda. Kamień ma rysy przypominające mapę.' },
    { n: 11, x: 55, y: 80, rune: 'ᛁ', name: 'Isa',     lore: 'Przy południowym wejściu do Fjordgardu. Mróz wokół niego silniejszy niż zimą.' },
    { n: 12, x: 48, y: 57, rune: 'ᛃ', name: 'Jera',    lore: 'Ukryty za kaplicą na cmentarzu Vargheim. Ostatni i najtrudniejszy do znalezienia.' },
  ].map(({ n, x, y, rune, name: runeName, lore }) => ({
    id: `wl-rune-stone-${n}`,
    name: `Kamień Runiczny ${n}/12 — ${rune} ${runeName}`,
    nordic_name: `Rúnasteinn ${n}`,
    x, y,
    icon: '🪨', type: 'secret', region: 'Cały Świat',
    marker_type: 'secret', visibility: 'visible', state: 'available',
    short_desc: `Jeden z dwunastu starożytnych kamieni runicznych. Runa ${runeName} (${rune}).`,
    description_short: `Kamień ${n}/12 · ${rune} ${runeName}`,
    full_lore: lore + ' Każdy z dwunastu kamieni zawiera fragment inskrypcji. Gdy zbierzesz wszystkie dwanaście — zrozumiesz co razem tworzą.',
    npcs: q([]),
    actions: q([`Dotknij runy ${runeName}`, 'Przepisz fragment inskrypcji', 'Zbadaj magicznie']),
    discovery_reward_xp: 15, discovery_reward_skirniry: 8,
    quests: q([
      {
        id: `quest-rune-stone-${n}`,
        title: `Kamień Runiczny ${n}/12`,
        category: 'Meta-tajemnica', difficulty: 'Łatwy',
        discordChannel: '#tajemnica-run',
        reward: { points: 10, xp: 15, skirniry: 8, item: `Fragment Inskrypcji ${n}/12` },
        description: `Jeden z dwunastu starożytnych kamieni. Dotknij runy ${runeName} i zapisz fragment. Dopiero gdy zbierzesz wszystkie dwanaście — zobaczysz co tworzą razem.`,
        initialBotMessage: `🪨 **[TMD BOT - KAMIEŃ RUNICZNY ${n}/12]**\nKamień chłodny. Runa ${rune} (${runeName}) pulsuje gdy kładziesz dłoń.\n*Fragment inskrypcji ujawnia się tylko przy dotyku.*\n\nCo robisz:`,
        suggestedActions: [
          { label: `✋ Dotknij runy ${runeName}`, cmd: `/dotknij runa-${runeName.toLowerCase()} kamien-${n}` },
          { label: '📜 Przepisz fragment do dziennika', cmd: `/przepisz fragment-inskrypcja-${n}` },
          { label: '🔮 Zbadaj połączenia z innymi kamieniami', cmd: `/detekcja kamien-runiczny-siec` },
        ],
        solutionKeywords: ['dotknij', 'runa', 'przepisz', 'fragment', runeName.toLowerCase()],
        successMessage: `✨ Fragment ${n}/12 zapisany. ${n < 12 ? `Brakuje jeszcze ${12 - n} kamieni.` : 'WSZYSTKIE 12 ODKRYTE! Ich pozycje tworzą na mapie ogromną runę. Odblokowano: TRZYNASTY KAMIEŃ.'}`,
        failMessage: `❄️ Runa nie reaguje. Upewnij się że stoisz bezpośrednio przy kamieniu.`,
      },
    ]),
  })),

// ═══════════════════════════════════════════════════════════════════
//  TRZYNASTY KAMIEŃ — Finał meta-tajemnicy
// ═══════════════════════════════════════════════════════════════════

  {
    id: 'wl-stone-13',
    name: 'Trzynasty Kamień',
    nordic_name: 'Þrettándi Steinn',
    x: 50, y: 52,
    icon: '🌑', type: 'secret', region: 'Centrum',
    marker_type: 'secret', visibility: 'hidden', state: 'locked',
    short_desc: 'Nieistniejąca lokacja — pojawia się po zebraniu wszystkich 12 kamieni',
    description_short: 'FINAŁ META-TAJEMNICY · 13. kamień',
    full_lore: 'Trzynasty kamień nie istnieje na żadnej mapie. Jego pozycja — geometryczny środek runi tworzonej przez dwanaście kamieni — to miejsce, w którym coś kryje się pod ziemią. Coś, czego Durmstrang zbudował się na szczycie. Celowo.',
    npcs: q(['Pierwsza Arcymistrzyni (echo)', 'Strażnik Fundamentu']),
    actions: q(['Wykop Trzynasty Kamień', 'Zejdź pod Twierdzę', 'Odczytaj kompletną inskrypcję']),
    discovery_reward_xp: 100, discovery_reward_skirniry: 60,
    quests: q([
      {
        id: 'quest-stone-13-final',
        title: 'TRZYNASTY KAMIEŃ',
        category: 'Finał Meta-tajemnicy', difficulty: 'Legendarny',
        discordChannel: '#trzynasty-kamien',
        reward: { points: 100, xp: 300, skirniry: 100, item: 'Prawda o Durmstrangu' },
        description: 'FINAŁ: 12/12 fragmentów zebrano. Pozycje tworzą runę Othalan — dom, dziedzictwo. Środek runi wskazuje na fundament Twierdzy. Pod piętrem zerowym jest coś, co było tam zanim powstał Durmstrang.',
        initialBotMessage: '🌑 **[TMD BOT - TRZYNASTY KAMIEŃ · FINAŁ META-TAJEMNICY]**\nKompletna inskrypcja: *"To, co zbudowano na fundamencie zapomnienia, będzie pamiętane przez kamień."*\nPod Twierdzą: wejście. Nowe. Albo bardzo stare.\n\nJak schodzisz w głąb:',
        suggestedActions: [
          { label: '🕯️ Zstąp z runiczną latarnią', cmd: '/zejdz latarnia-runiczna pod-twierdze' },
          { label: '📜 Wypowiedz formułę kompletnej inskrypcji', cmd: '/inkantacja pelna-inskrypcja-12' },
          { label: '🤝 Idź z grupą — quest grupowy', cmd: '/grupowy-quest trzynasty-kamien' },
        ],
        solutionKeywords: ['inskrypcja', 'fundament', 'zejdz', 'latarnia', 'twierdza', 'kamien'],
        successMessage: '✨ Pod fundamentami Durmstrangu: resztki szkoły starszej niż Twierdza. Jej ostatnia Arcymistrzyni zapieczętowała się tutaj z całą wiedzą, którą Durmstrang chciał wymazać. Pieczęć czekała na kogoś, kto poszuka.',
        failMessage: '❄️ Inskrypcja niekompletna. Potrzebujesz wszystkich 12 fragmentów.',
      },
    ]),
  },

// ═══════════════════════════════════════════════════════════════════
//  UKRYTE LOKACJE
// ═══════════════════════════════════════════════════════════════════

  {
    id: 'wl-hidden-chatka',
    name: 'Chatka Bez Drzwi',
    nordic_name: 'Dyrlaushús',
    x: 14, y: 46,
    icon: '🏚️', type: 'secret', region: 'Daleki Zachód',
    marker_type: 'secret', visibility: 'hidden', state: 'locked',
    short_desc: 'Chatka widoczna tylko gdy nosisz odpowiednią runę',
    description_short: 'Ukryta · pojawia się po Runie Isa',
    full_lore: 'Nie ma w niej drzwi bo nie potrzebuje drzwi. Mieszka w niej ktoś, kto nie chce żeby go znajdowali. Ty ją widzisz. To wymaga wyjaśnienia.',
    npcs: q(['Bezimienny Pustelnik']),
    actions: q(['Wejdź przez ścianę', 'Porozmawiaj z Pustelnikiemm', 'Zbadaj kolekcję run']),
    discovery_reward_xp: 35, discovery_reward_skirniry: 20,
    quests: q([
      {
        id: 'quest-hidden-chatka',
        title: 'Bezimienny',
        category: 'Sekret', difficulty: 'Trudny',
        discordChannel: '#sekrety-polnocy',
        reward: { points: 40, xp: 120, skirniry: 30, item: 'Runa Niewidzialności' },
        description: 'Pustelnik nie ma imienia — oddał je jako cenę. Twierdzi, że wie co wydarzyło się w Havnhold, Skallgardzie i dlaczego Durmstrang udaje, że ich nie ma.',
        initialBotMessage: '🏚️ **[TMD BOT - CHATKA BEZ DRZWI]**\nPustelnik siedzi tyłem.\n*„Wiedziałem, że ktoś tu dotrze. Nie wiedziałem kiedy."*\n\nO co pytasz:',
        suggestedActions: [
          { label: '❓ Zapytaj o Havnhold', cmd: '/zapytaj pustelnik havnhold' },
          { label: '📜 Zapytaj o Skallgard', cmd: '/zapytaj pustelnik skallgard' },
          { label: '🔮 Zapytaj o Trzynasty Kamień', cmd: '/zapytaj pustelnik trzynasty-kamien' },
        ],
        solutionKeywords: ['pustelnik', 'havnhold', 'skallgard', 'kamien'],
        successMessage: '✨ Pustelnik mówi przez trzydzieści minut. Opisuje sieć — questy, miejsca i tajemnice, które nie są przypadkowe. Ktoś to ułożył. I zostawił dla uczniów, którzy będą wystarczająco ciekawi.',
        failMessage: '❄️ *„Za wcześnie na to pytanie. Wróć gdy będziesz wiedział więcej."*',
      },
    ]),
  },

  {
    id: 'wl-hidden-ogrod',
    name: 'Zamarznięty Ogród',
    nordic_name: 'Ísgarðr',
    x: 42, y: 66,
    icon: '🌸', type: 'secret', region: 'Centrum-Południe',
    marker_type: 'secret', visibility: 'hidden', state: 'locked',
    short_desc: 'Ogród z kwiatami kwitnącymi pod lodem — dostępny przez Zielarstwo',
    description_short: 'Ukryty · dostępny po questach Zielarki',
    full_lore: 'Pod warstwą lodu kwitną kwiaty, których nikt nie siał. Rosną od tysiąca lat bez słońca i gleby. Są czymś innym — składnikiem, którego nie ma w żadnym przepisie, bo nikt nie wiedział gdzie szukać.',
    npcs: q([]),
    actions: q(['Zbierz lodowe kwiaty', 'Zbadaj magię ogrodu', 'Poczekaj do wschodu słońca']),
    discovery_reward_xp: 30, discovery_reward_skirniry: 18,
    quests: q([
      {
        id: 'quest-hidden-ogrod',
        title: 'Kwiat pod lodem',
        category: 'Zielarstwo', difficulty: 'Średni',
        discordChannel: '#sekrety-polnocy',
        reward: { points: 30, xp: 90, skirniry: 25, item: 'Ísblóm — Lodowy Kwiat' },
        description: 'Zielarka Skadi wysłała po Ísblóm — kwiat, który „rośnie tam, gdzie lód i życie są jednym".',
        initialBotMessage: '🌸 **[TMD BOT - ZAMARZNIĘTY OGRÓD]**\nPod lodem: kolory. Czerwień, błękit, złoto. Kwiaty kwitną w temperaturze poniżej zera.\n\nJak zbierasz bez niszczenia:',
        suggestedActions: [
          { label: '🌡️ Zaklęcie Tepor — lokalnie ogrzej lód', cmd: '/rzut tepor lod-kwiat' },
          { label: '✂️ Użyj runicznych nożyczek', cmd: '/uzyj runiczne-nozyczki kwiat' },
          { label: '🙏 Poproś ogród o pozwolenie', cmd: '/prosba ogrod-zezwolenie kwiat' },
        ],
        solutionKeywords: ['tepor', 'nozyczki', 'prosba', 'kwiat', 'ogrod', 'isblom'],
        successMessage: '✨ Kwiat oddaje się bez walki. Lodowaty, ale ciepły w środku. Skadi będzie zadowolona.',
        failMessage: '❄️ Kwiat cofa się pod lód. Ogród nie jest przychylny. Zmień podejście.',
      },
    ]),
  },

  {
    id: 'wl-hidden-jaskinia-smok',
    name: 'Jaskinia Białego Smoka',
    nordic_name: 'Hvítdrekahellir',
    x: 56, y: 12,
    icon: '🐉', type: 'secret', region: 'Daleka Północ',
    marker_type: 'secret', visibility: 'hidden', state: 'locked',
    short_desc: 'Legendarny punkt — jaskinia Białego Smoka z Frostfang. Endgame.',
    description_short: 'Ukryta · endgame · tylko dla najwyżej levlowanych',
    full_lore: 'Biały Smok nie jest agresywny. Biały Smok jest stary. I zmęczony. I rozmawia. Ale tylko z kimś, kto dotarł tu samodzielnie, bez pomocy, bez map, bez przewodników. Czyli prawie z nikim.',
    npcs: q(['Biały Smok Fafnúmr']),
    actions: q(['Wejdź do jaskini', 'Porozmawiaj ze Smokiem', 'Wysłuchaj historii Frostfang']),
    discovery_reward_xp: 75, discovery_reward_skirniry: 45,
    quests: q([
      {
        id: 'quest-smok-fafnumr',
        title: 'Rozmowa z Fafnúmrem',
        category: 'Endgame', difficulty: 'Legendarny',
        discordChannel: '#sekrety-polnocy',
        reward: { points: 100, xp: 300, skirniry: 80, item: 'Łuska Białego Smoka' },
        description: 'ENDGAME: Fafnúmr jest ostatnim żywym Białym Smokiem Północy. Pamięta czasy przed Durmstrangiem. I przed Skallgardem. Chce porozmawiać — bo od trzystu lat nikt nie przychodził.',
        initialBotMessage: '🐉 **[TMD BOT - JASKINIA BIAŁEGO SMOKA]**\nFafnúmr jest ogromny i biały jak śnieg. Patrzy na ciebie bez ruchu.\n*„Przyszedłeś sam. To rzadkie."*\n*„Co chcesz wiedzieć?"*\n\nO co pytasz:',
        suggestedActions: [
          { label: '🏛️ Zapytaj o Skallgard', cmd: '/zapytaj fafnumr skallgard' },
          { label: '🧊 Zapytaj o Frostfang', cmd: '/zapytaj fafnumr frostfang-historia' },
          { label: '📜 Zapytaj o Trzynasty Kamień', cmd: '/zapytaj fafnumr trzynasty-kamien' },
        ],
        solutionKeywords: ['fafnumr', 'skallgard', 'frostfang', 'kamien', 'zapytaj'],
        successMessage: '✨ Fafnúmr mówi przez godzinę. Historia świata, jakiej nie ma w żadnej księdze Durmstrangu — bo Durmstrang ją wymazał. Każde pytanie to kolejna warstwa prawdy.',
        failMessage: '❄️ *„Wróć gdy będziesz gotowy na odpowiedzi."*',
      },
    ]),
  },

];
